site_name: BaRhElMaNhG
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Math:
      - Unit 1 Numbers and operations on them:
          - Lesson 1 Proportion: math/unit1/lesson1.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/mathjax-config.js

markdown_extensions:
  - pymdownx.arithmatex:
      inline_math: true
      tex_inline_wrap: ["$", "$"]
      tex_block_wrap: ["$$", "$$"]

