site_name: BaRhElMaNhG
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections


nav:
  - Home: index.md
  - Math:
      - Unit 1:
          - Lesson 1: math/unit1/lesson1.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML
