site_name: BaRhElMaNhG
docs_dir: 'docs'

theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections  # This enables sectioned navigation

  palette:
    primary: orange
    accent: green



nav:
  - Home: index.md
  - Math:
    - Unit 1 Proportion: 
      - Lesson 1 Proportion: math/unit1/lesson1.md
      - Exercise 1 Proportion: math/unit1/exercise1.md
      - Lesson 2 Scale Drwaing: math/unit1/lesson2.md
      - Exercise 2 Scale Drwaing: math/unit1/exercise2.md
      - Lesson 3 Proportional Division: math/unit1/lesson3.md
      - Exercise 3 Proportional Division: math/unit1/exercise3.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

