site_name: BaRhElMaNhG

theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections  # This enables sectioned navigation

nav:
  - Home: index.md
  - Math:
    - Unit 1 Proportion: 
      - Lesson 1 Proportion: math/unit1/lesson1.md
      - Exercise 1 Proportion: math/unit1/exercise1.md
      - Lesson 2 Applications of Ratio and Proportion: math/unit1/lesson2.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/chart.js
  - attr_list
  - https://unpkg.com/leaflet@1.7.1/dist/leaflet.js

extra_css:
  - https://unpkg.com/leaflet@1.7.1/dist/leaflet.css
