site_name: BaRhElMaNhG
docs_dir: 'docs'

theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections  # This enables sectioned navigation

nav:
  - Home: index.md
  - Math:
    - Unit 1 Proportion: 
      - Lesson 1 Proportion: math/unit1/lesson1.md
      - Exercise 1 Proportion: math/unit1/exercise1.md
      - Lesson 2 Applications of Ratio and Proportion: math/unit1/lesson2.md
      - Exercise 2 Applications of Ratio and Proportion: math/unit1/exercise2.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
