site_name: BaRhElMaNhG
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: assets/logo.png
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Math:
      - Unit 1 Numbers and operations on them:
          - Lesson 1 Proportion: math/unit1/lesson1.md




